
DROP TABLE tasks;
CREATE TABLE tasks(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nomTasca VARCHAR(255) NOT NULL,
    sparks INTEGER,
    dataLimit TIMESTAMP,
    dataCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dataUpdated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    urlImage VARCHAR(500)
)
